### ISSUE TITLE
Create vouchers

### ISSUE THREAD

**Issue by tirannilakshe** [malle-pietje/UniFi-API-browser#10]
need to create vouchers and print vouchers from api

**Comment by malle-pietje** [comment]
Basically what you need to do is create the vouchers, then get the newly created vouchers and their details, format them on an html page and print. I can help with how to use the API client but not with the other elements; that comes down to basic HTML, CSS and PHP skills.

**Comment by malle-pietje** [comment]
@tirannilakshe FYI, there was a bug in the `create_vouchers()` function/method that is now fixed.

**Comment by tiransa** [comment]
i have done voucher creating. but there is a little problem. that i can only create one time use vouchers only. how can i generate multi use vouchers

**Comment by malle-pietje** [comment]
Are you able to create them in the controller? If so, how? I don't use them myself....

**Comment by tiransa** [comment]
yes. when i create voucher in controller there is a option to select multi
use

**Comment by tiransa** [comment]
![untitled](https://cloud.githubusercontent.com/assets/13179900/20068364/7189cd20-a53e-11e6-9caf-eda752577b79.png)

**Comment by malle-pietje** [comment]
Ah, I see. Let me see how to efficiently enable this in the API client.

**Comment by tiransa** [comment]
there are some other things also how to delete vouchers, can i block and unblock guest by mac address

**Comment by malle-pietje** [comment]
I've added the multi-use/single-use option to the `create_voucher()` function:
```
   /**
    * Create voucher(s)
    * -----------------
    * returns an array of vouchers codes (NOTE: without the "-" in the middle) by calling the stat_voucher method
    * required parameter <minutes> = minutes the voucher is valid after activation
    * optional parameter <number_of_vouchers_to_create> = number of vouchers to create, default value is 1
    * optional parameter <quota> = single-use or multi-use vouchers, string value '0' is for multi-use, '1' is for single-use
    * optional parameter <note> = note text to add to voucher when printing
    * optional parameter <up> = upload speed limit in kbps
    * optional parameter <down> = download speed limit in kbps
    * optional parameter <MBytes> = data transfer limit in MB
    */
   public function create_voucher($minutes, $number_of_vouchers_to_create = 1, $quota = '0', $note = NULL, $up = NULL, $down = NULL, $MBytes = NULL) {
      if (!$this->is_loggedin) return FALSE;
      $return = array();
      $json   = array('cmd' => 'create-voucher', 'expire' => $minutes, 'n' => $number_of_vouchers_to_create, 'quota' => $quota);
      /**
       * if we have received values for note/up/down/MBytes we append them to the payload array to be submitted
       */
      if (isset($note))   $json['note'] = trim($note);
      if (isset($up))     $json['up'] = $up;
      if (isset($down))   $json['down'] = $down;
      if (isset($MBytes)) $json['bytes'] = $MBytes;
      $json            = json_encode($json);
      $content_decoded = json_decode($this->exec_curl($this->baseurl.'/api/s/'.$this->site.'/cmd/hotspot','json='.$json));
      if ($content_decoded->meta->rc == 'ok') {
         if (is_array($content_decoded->data)) {
            $obj = $content_decoded->data[0];
            foreach ($this->stat_voucher($obj->create_time) as $voucher)  {
               $return[]= $voucher->code;
            }
         }
      }
      return $return;
   }
```
I would appreciate if you could test this in your environment and report back whether this works or not.

TIA

**Comment by malle-pietje** [comment]
@tirannilakshe  A function/method to delete vouchers can certainly be added, I will do that with the new release of the API client which will also include the improved `create_voucher()` function after your confirmation that the above modification works.

For blocking/unblocking clients the `block_sta()` and `unblock_sta()` functions should do the trick. Have you already tried that?

**Comment by tiransa** [comment]
yes it is ok now thank you

**Comment by malle-pietje** [comment]
You're welcome. Thanks for the feedback; I'll update the class and add the voucher delete function shortly.

**Comment by malle-pietje** [comment]
@tiransa I have pushed a new version of the API client class and the API browser tool. Could you please check whether the new `revoke_voucher()` function/methods does what you wanted to achieve with regard to voucher deletion?

**Comment by tiransa** [comment]
revoke_voucher() ok now how about disconnect and extend in guest actions

**Comment by malle-pietje** [comment]
Thanks for the feedback. For disconnect/extend, see my comment from 2 days ago.

**Comment by tiransa** [comment]
hello, can i create hotspot operator from this API Class

**Comment by malle-pietje** [comment]
that has not yet been implemented, only the function to list the operators `list_hotspotop()`

**Comment by tiransa** [comment]
can you do that soon please

**Comment by malle-pietje** [comment]
I'm quite busy at the moment so this will take at least a week or two

**Comment by tiransa** [comment]
ok i will wait for that. thank you

**Comment by malle-pietje** [comment]
@tiransa This function should let you create hotspot operators. Could you please test and confirm back if it's working?
```
    /**
     * Create hotspot operator
     * -----------------
     * returns TRUE upon success
     * required parameter <name>       = name for the hotspot operator
     * required parameter <x_password> = clear text password for the hotspot operator
     * optional parameter <note>       = note to attach to the hotspot operator
     */
    public function create_hotspotop($name, $x_password, $note = NULL) {
        if (!$this->is_loggedin) return FALSE;
        $return = FALSE;
        $json   = array('name' => $name, 'x_password' => $x_password);
        /**
         * if we have received a value for note, we append it to the payload array to be submitted
         */
        if (isset($note)) $json['note'] = trim($note);
        $json            = json_encode($json);
        $content_decoded = json_decode($this->exec_curl($this->baseurl.'/api/s/'.$this->site.'/rest/hotspotop','json='.$json));
        if (isset($content_decoded->meta->rc)) {
            if ($content_decoded->meta->rc == 'ok') {
                $return = TRUE;
            }
        }

        return $return;
    }
```

**Comment by malle-pietje** [comment]
@tiransa If it works I will include it in the release I have ready for the API Browser and the API client class.

**Comment by malle-pietje** [comment]
Added `create_hotspotop()` function/method several commits ago.
