### ISSUE TITLE
Change PSK function

### ISSUE THREAD

**Issue by Phisherman** [malle-pietje/UniFi-API-browser#12]
Hi,

There is already the `set_wlansettings($wlan_id, $name, $x_passphrase)` function. But it would be nice to have also an `set_psk` function if you only want to change the psk and cannot provide the wlan's name without accessing the unifi api to get the corresponding wlan name.

**Comment by malle-pietje** [comment]
@Phisherman I haven't checked yet if that would work, but you will need to first access the API with the `list_wlanconf()` function/method anyway to get the wlan_id.

**Comment by Phisherman** [comment]
@malle-pietje I already have the wlan_id. I only store the wlan_id in the db because the other data could change.

**Comment by malle-pietje** [comment]
Ah, I see. Let me check whether that would work. If so, I'll update the class and publish on github. I also have some other updates that need to be added so I'll try and combine these.

**Comment by Phisherman** [comment]
@malle-pietje I appreciate it!

**Comment by malle-pietje** [comment]
@Phisherman I just tried my modified class and it works; `name` is now an optional parameter for the `set_wlansettings` function/method. I will update the class on github in a few minutes so please test API class version 1.0.6 when you have the opportunity, and please let me know here what the results are.

**Comment by Phisherman** [comment]
@malle-pietje Works like a charm.

**Comment by malle-pietje** [comment]
Glad to hear!
