### ISSUE TITLE
connect to existing unifi cloud key

### ISSUE THREAD

**Issue by stefanmei** [malle-pietje/UniFi-API-browser#15]
hi this is my config file:

$controlleruser     = 'xx'; // the user name for access to the UniFi Controller
$controllerpassword = 'xx'; // the password for access to the UniFi Controller
$controllerurl      = 'unifi.ubnt.com'; // full url to the UniFi Controller, eg. 'https://22.22.11.11:8443'
$controllerversion  = '5.2.9'; // the version of the Controller software, eg. '4.6.6' (must be at least 4.0.0)

but i cannot select a site in the browser api

**Comment by malle-pietje** [comment]
Connecting to a Cloud Key through unifi.ubnt.com will not work, it will only work if the system on which you installed the API Browser tool has direct IP connectivity with the Cloud Key. The site unifi.ubnt.com uses WebRTC as very neat trick which the API client (and cURL) does not leverage.

**Comment by stefanmei** [comment]
thank you. so i go dns

**Comment by malle-pietje** [comment]
if you have dynamic IP, yes.
