### ISSUE TITLE
N number of multi use voucher

### ISSUE THREAD

**Issue by tirannilakshe** [malle-pietje/UniFi-API-browser#17]
when create multi use voucher user can use unlimited devise connect by that voucher. i want to limit that to   few devices. some forums i show that can do from api.

**Comment by malle-pietje** [comment]
As far as I know there is no way to limit a multi-use voucher to n devices with the current controller and hotspot manager, therefore this is also not possible with the API. If I'm mistaken, please point me to any topics or messages on the community explaining how this should work.

**Comment by tirannilakshe** [comment]
Re: Multi User Voucher - Limit to x Devices?
Options
<https://community.ubnt.com/t5/UniFi-Wireless/Multi-User-Voucher-Limit-to-x-Devices/td-p/959143#>

‎08-13-2014 11:20 AM

UniFi hotspot system do not allow that, end of line. There's only the
single-use or multi-use options.

You can, however, code your own portal and have whatever rule you want/need
to get applied on your guest, that includes limiting the number of users
per voucher. That portal could be easily integrated with UniFi using the
'External Portal' option. Portal code samples are available on the forums,
just look at them. The codes to interact with the controller are quite
simple, generating and managing the vouchers would definitely be much
harder than that.


Solutti Tecnologia Ltda - Goiânia/Goiás/Brazil
www.solutti.com.br

did my answer helped you ? if yes, i would love your kudos on it [image:
Man Happy]

**Comment by malle-pietje** [comment]
Ah, that discussion. The poster is correct that you can do this with a custom external portal. This means you will need to build the voucher logic yourself and interface with the controller through the API for which you could use the PHP API client class which comes bundled with the API Browser tool.

**Comment by malle-pietje** [comment]
Since this is out of scope for the API Browser tool I can offer you paid help with this if needed.

**Comment by tirannilakshe** [comment]
ok send me product details with pricess

**Comment by malle-pietje** [comment]
Thanks! Shall we continue this conversation offline? You can contact me by email at erik ATT artofwifi DOTT net.
