### ISSUE TITLE
clients, guests and users

### ISSUE THREAD

**Issue by jftuga** [malle-pietje/UniFi-API-browser#20]
What is the difference between listing online clients, guests and users? Is one used with an open SSID and the other used for when there is a password required?

**Comment by makuser** [comment]
Are you even using UniFi?

**Comment by jftuga** [comment]
Yes.

**Comment by makuser** [comment]
Well then you do know what a Guest and a User is. In this API browser, it's exactly the same.

**Comment by jftuga** [comment]
So does Client = Guest + User?

**Comment by makuser** [comment]
> So does Client = Guest + User?

A client is a normal UniFi client. So anything connected via wireless or wired.
A guest is a client, that's connected to a network which is using the UniFi "Guest policies".
A user is a client, that's connected to a network which is NOT using the UniFi "Guest policies".

**Comment by malle-pietje** [comment]
Correct, and as @makuser said, it's the same data model/logic as with the controller UI. This kind of questions BTW, is exactly the purpose of the API Browser tool; when in doubt how to leverage the API collections/endpoints, compare the data from the API Browser with the controller UI😉

**Comment by malle-pietje** [comment]
Op top of that, a client can both be guest and user, though not at the same time. Only when switching SSID types.

**Comment by jftuga** [comment]
Thank you for the explanation.
