### ISSUE TITLE
Mobile devices disconnected when authorizing

### ISSUE THREAD

**Issue by mbassan** [malle-pietje/UniFi-API-browser#24]
First of all, let me congratulate you for the excellent library. Thanks!

I have created an external captive portal and successfully authorized devices. 

However, when my PHP code sends the authorize_guest($mac, $duration) command, the WiFi for the mobile device in question is actually disconnected. 

This happens on both Android and iOS as far as I can tell.

Here is the code I am using:
```
$controlleruser = $CFG->unifi_user;
$controllerpassword = $CFG->unifi_pass;
$controllerurl = 'https://'.$server.':'.$CFG->unifi_port;
$controllerversion = '5.4.11';
$cookietimeout = '3600';
$theme = 'bootstrap';
$debug = false;
$duration = $CFG->unifi_minutes;
$note = '';
$site_id = 'default';

require_once('class.unifi.php');

$unifidata      = new unifiapi($controlleruser, $controllerpassword, $controllerurl, $site_id, $controllerversion);
$set_debug_mode = $unifidata->set_debug($debug);
$loginresults   = $unifidata->login();
/**
 * To add note to a new device we need to do the following before authorizing the device:
 * - first block the device to get an entry in the user collection
 * - get the device id from the user collection
 * - add note to the device
 * - then unblock the device again
 */
$block_result   = $unifidata->block_sta($mac);
$getid_result   = $unifidata->stat_client($mac);
$user_id        = $getid_result[0]->_id;
$note_result    = $unifidata->set_sta_note($user_id, $note);
$unblock_result = $unifidata->unblock_sta($mac);
/**
 * then we authorize the device for the requested duration
 */
$auth_result = $unifidata->authorize_guest($mac, $duration);
/**
 * provide feedback in json format
 */
return $auth_result;
```

**Comment by malle-pietje** [comment]
Thanks, glad this library can be of help.

I would suggest to first comment out the 5 lines of code immediately above the actual auth request so that the auth request is called directly after login. This example is meant for specific situations but maybe not useful for your scenario.

If that does not solve the issue, it will help to track what happens in the event log on the controller for this specific site.

**Comment by mbassan** [comment]
Thanks @malle-pietje . That solved the issue. I assumed that those lines were necessary for general authorization.
