### ISSUE TITLE
The file config.php is not readable or does not exist.' . '

### ISSUE THREAD

**Issue by lesvaches** [malle-pietje/UniFi-API-browser#25]
The file config.php is not readable or does not exist.' . '

**Comment by malle-pietje** [comment]
This error message is quite self-explanatory: either you have not followed the installation instructions from the README file or the newly created config.php file is not readable by the webserver:
**"credentials for access to the UniFi Controller API need to be configured in the file named config.template.php which should be copied/renamed to config.php before using the UniFi API browser tool"**
