### ISSUE TITLE
limitation of multi use voucher

### ISSUE THREAD

**Issue by tiransa** [malle-pietje/UniFi-API-browser#27]
dear friend,

already i asked question about how to limit multi use voucher. now that have developed in unifi controller 5.5.11 beta version. so please check that and quickly update api browser tool.

**Comment by malle-pietje** [comment]
I currently do not have time to work on that so may I suggest you submit a pull-request for this and/or share more of the results of your research.

**Comment by tiransa** [comment]
ok i ill try to do that. when you have free time, check that

**Comment by tiransa** [comment]
in controller version 5.5.11 there is fetcher to select number of device as
following image. i want to add this to api browser
[image: Inline image 1]

**Comment by malle-pietje** [comment]
The image isn't visible...

**Comment by tiransa** [comment]
check that i have added again

**Comment by malle-pietje** [comment]
So you want this added to the API client class (not the API browser, that would not make sense) to allow you to also modify that attribute when creating vouchers?

**Comment by tiransa** [comment]
yes

**Comment by malle-pietje** [comment]
OK, I'll see what's possible. As I said, I'm extremely busy with paid work at the moment so it can take a while before I get to it.

**Comment by tiransa** [comment]
i am waiting for that

**Comment by malle-pietje** [comment]
I just looked into voucher creation on 5.5.17 and I see no major change other than the way expiry is handled.

Creating multi-use vouchers still works the same as with previous versions so using the `create_vouchers()` will work fine for your purpose. Pay special attention to the `quota` parameter...:
https://github.com/malle-pietje/UniFi-API-browser/blob/master/phpapi/class.unifi.php#L859-L887

**Comment by tiransa** [comment]
yes. it is working. thank you dear

**Comment by malle-pietje** [comment]
Thanks for confirming!
