### ISSUE TITLE
How to reach controller from outside network

### ISSUE THREAD

**Issue by mbassan** [malle-pietje/UniFi-API-browser#29]
Hey man, it's me again.

This is not related to your repo directly - I just can't find the answer anywhere else:

What IP do I call to reach the controller from outside the LAN? For example, if my hotspot script is on Amazon AWS and the controller is behind an Edge Router, how would I determine the right IP to call to authorize the device on the controller?

You're my only hope!

**Comment by malle-pietje** [comment]
Use the public IP address of the ER. If the IP address is dynamic I suggest you set up some dynamic dns service such as http://dyn.com/dns/, then refer to public domain name.

**Comment by malle-pietje** [comment]
This does assume that port forwarding rules are in place to request to port 8443 to the internal IP address of the controller.

**Comment by mbassan** [comment]
Excellent, thanks man! Was having connection problems in many locations and I wanted to make sure that the controller would be accessible at all in theory - and that I wasn't trying something impossible.

**Comment by malle-pietje** [comment]
You're welcome.
