### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by swap-ets** [malle-pietje/UniFi-API-browser#33]
Hi,

I followed your instructions however I am getting a 500 error when I try and access index.php, I have copied info.php to the /var/www/html/UniFi-API-browser directory ant that works fine, can you point me in any directions?

Regards

Sean

**Comment by malle-pietje** [comment]
An 500 error is an Internal Server Error. To troubleshoot this you need to look at your PHP error log. Normally when running PHP with apache2 this will be `/var/log/apache2/error.log` or similar.

Please share the relevant lines from this error log if you aren't able to figure out yourself what the exact issue is and fix it.

**Comment by swap-ets** [comment]
Hi the error I get is;
[[Tue Jun 27 07:55:55.879362 2017] [:error] [pid 2398] [client 10.0.1.223:59061] PHP Fatal error:  Call to undefined function curl_version() in /var/www/html/UniFi-API-browser/index.php on line 97
Line 97 in index.php is - $curl_info    = curl_version();

Cheers

Sean

**Comment by malle-pietje** [comment]
OK, that means you haven't installed the php-curl module. Just follow the instructions for your operating system and you should be fine.

BTW, I had already prepared a code update where this error is caught and displayed in the browser so that should help future users to troubleshoot this. I will push this commit later today.

**Comment by swap-ets** [comment]
Thanks,
If I check on my unifi server with curl -V the result returned says I have curl 7.38.0 is there anything else I need to do to make it work with php?

**Comment by swap-ets** [comment]
HAve fixed it, I installed curl nor curl-php, have now installed it and it works fine, thanks for all your help

**Comment by malle-pietje** [comment]
Good to hear, thanks for the feedback!

**Comment by swap-ets** [comment]
One final question, is there anyway of listing devices that connected a specific SSID?

**Comment by malle-pietje** [comment]
Yes but not in a straightforward manner; for currently connected devices you can process the results from the `list_clients()` method/function. For historical (not currently connected state) data you will need to process the results from the `list_events()` method/function.

The API Browser tool was specifically developed to help you figure this out by browsing through the results of the various API endpoints.

**Comment by swap-ets** [comment]
Thanks a lot, will have a play!

**Comment by malle-pietje** [comment]
Good luck!
