### ISSUE TITLE
api.err.NoSiteContext

### ISSUE THREAD

**Issue by bandroidx** [malle-pietje/UniFi-API-browser#35]
am getting the following error trying to use this:

 DEBUG api    - /api/login finished (647 handling, 1 rendering)
[2017-07-23 22:45:36,782] <webapi-179> INFO  api    - [api] api.err.NoSiteContext: /api/s/Default/cmd/stamgr
[2017-07-23 22:45:36,784] <webapi-179> DEBUG api    - /api/s/Default/cmd/stamgr finished (1 handling, 0 rendering)

my site is definetly called 'Default'

**Comment by bandroidx** [comment]
i changed site name to test and tried again, same error:

-------URL & PAYLOAD---------
https://127.0.0.1:8443/api/s/test/cmd/stamgr
json={"cmd":"authorize-guest","mac":"88:79:7e:0a:80:0d","minutes":10}
----------RESPONSE-----------
{ "data" : [ ] , "meta" : { "msg" : "api.err.NoSiteContext" , "rc" : "error"}}
-----------------------------
</pre>Last error message: api.err.NoSiteContext


that mac address IS on an AP on the site right now.

**Comment by bandroidx** [comment]
It looks like my issue is i was using "Default" at first instead of "default" (I was using the actual site name).  Then even though i changed the site to "test", it stayed as "default"  I changed to lower case and it seems to be working now.

Thanks.

BTW, is there any recent example implementation to use this to authenticate with captive portal?  the example on the unifi kb is ancient.  thanks

**Comment by malle-pietje** [comment]
@bandroidx glad to hear you figured out what was going on:smile: I'll see that I explain in further detail in the README where you can find the `site-id` value.

Regarding your question about the captive portal example; I believe one of the UBNT forum members had adapted one of the captive portal examples to use this API client class. My best bet would be for you to post on the UBNT community (UniFi Wireless section has the most views) and ask who has an example using this API client class.

**Comment by bandroidx** [comment]
Hi, thanks for the reply.  I had posted on t he forums but someone offered a paid product to do captive portal login using the unifi api, I havent yet found an open source option.  I might try to develop something on my own if I am not able to find a working example (perhaps using the original old one as a starting point, yet its so old its not very helpful.)

If I make something it would be in symfony2, I was looking on packagist and I dont think anyone has made a symfony2 bundle of your library yet, unless you know of one? 

Regarding the site-id, googling my error didnt turn up much but one of the results a page down mentioned getting the correct site ID from the URL of the controller when you access it.  That is why I didnt delete my issue when I figured it out hoping someone might find my issue here and help them, updating the readme would probably be helpful too though.

Thankls

**Comment by malle-pietje** [comment]
Ah, OK.

I haven't yet added the API client class to Packagist although it is on my (long) TODO list. I am already using the class with a Laravel-based framework and that works great so Symfony should work for you as well.

I'll close the issue now but it will remain searchable for other users.

**Comment by bandroidx** [comment]
Great, thanks.  If I turn your class in to a working symfony 2 bundle I will put it on github and let you know.

**Comment by bandroidx** [comment]
Hi, I am wondering, are you the one who is selling the custom manager software?  I see you show a screenshot in your posts on the forum but then I see something similiar posted here: https://community.ubnt.com/t5/UniFi-Wireless/An-Extension-to-the-UniFi-Controller/m-p/1938653#M228704

but its not posted by you.

**Comment by malle-pietje** [comment]
Ah, that is software which I developed for that community member which is why screenshots of my own software look similar:-) He has received quite a lot of positive response from that post. This software is also using the Laravel-based framework.
