### ISSUE TITLE
API browser version 1.0.18 -  an update is available: 1.0.19

### ISSUE THREAD

**Issue by georgew88** [malle-pietje/UniFi-API-browser#37]
When cloning the recent version, the about tool always reports an update is available. The latest commit looks like the version const was never updated if I'm correct?

https://github.com/malle-pietje/UniFi-API-browser/blob/8de5e1e7cf676324f5e259b2a91e3ba4bd955ab9/index.php#L23

Thanks

**Comment by malle-pietje** [comment]
You're correct. Totally missed that omission. I will fix that right away.

**Comment by malle-pietje** [comment]
Done. Thanks!
