### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by facuxt** [malle-pietje/UniFi-API-browser#5]
Hello, im having this issue....

Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\unifi\index.php on line 452

i enabled debug mode, and this is what i get...

`Array
(
    [url] => https://XXXXXXXXXX:8443/api/login
    [content_type] => application/json;charset=UTF-8
    [http_code] => 200
    [header_size] => 332
    [request_size] => 217
    [filetime] => -1
    [ssl_verify_result] => 18
    [redirect_count] => 0
    [total_time] => 0.656
    [namelookup_time] => 0
    [connect_time] => 0
    [pretransfer_time] => 0.031
    [size_upload] => 42
    [size_download] => 41
    [speed_download] => 62
    [speed_upload] => 64
    [download_content_length] => 41
    [upload_content_length] => 42
    [starttransfer_time] => 0.656
    [redirect_time] => 0
    [redirect_url] => 
    [primary_ip] => XXXXXXXXXXX
    [certinfo] => Array
        (
        )

    [primary_port] => 8443
    [local_ip] => 172.16.10.166
    [local_port] => 53698
)

-----RESPONSE----------------
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
X-FRAME-OPTIONS: SAMEORIGIN
Set-Cookie: unifises=XXXXXXXXXXXX; Path=/; Secure; HttpOnly
Set-Cookie: csrf_token=XXXXXXXXXXXXXX; Path=/; Secure
Content-Type: application/json;charset=UTF-8
Content-Length: 41
Date: Wed, 06 Jul 2016 03:25:47 GMT

{ "data" : [ ] , "meta" : { "rc" : "ok"}}
-----------------------------`

Then i have a logout and seems to be ok aswell... what is going on? im trying unifi 5.1.1 Beta at the moment..

Thank you in advance...

**Comment by malle-pietje** [comment]
I have not seen this error before. Which PHP and cURL versions are you using?

**Comment by Demonslay335** [comment]
I was able to reproduce this. It is due to a bit of a session confusion.

I tried connecting to UBNT 3.2.10 at first (I know the comments say 4.0.0 minimum, but I had to try before going through that hassle :P). I started getting 401s from the API, which did not register with the code as being a failed request (it looks for 400, so must be difference from old controller versions), so it tries to continue. This allowed `list_sites()` to fail to get any sites, returning `false`, and storing it in the session.

I then upgraded the controller to 4.8.20, and refreshed the page. Since the session variable `$_SESSION['sites']` was already set, and equaled `false`, it sets `$sites = $_SESSION['sites'];`, which is what ends up breaking the `foreach` loop.

My suggestion is the change this line. on `index.php:182`

```
if (isset($_SESSION['sites']) || $_SESSION['sites'] === '') {
```

To:

```
if (isset($_SESSION['sites']) || empty($_SESSION['sites'])){
```

This allowed the sites from my updated controller to be pulled in correctly.

**Comment by malle-pietje** [comment]
Thanks for he feedback: seems to make sense to do it like this. I will test this change and include if all goes well.

**Comment by malle-pietje** [comment]
I checked the PHP docs and it turns out when using empty() there is no need to also use isset() as test.
http://php.net/manual/en/function.empty.php
Using empty() widens the scope of the test a bit to also test for "false" so it should do the trick.

**Comment by facuxt** [comment]
Hello, i updated my unifi controller to 5.2.2 and suddenly it works...  i put an .htpasswd simple http authorization on the app because it shows the ssh password of the aps and operator of hotspot... 
@malle-pietje very nice job dude!!!! i want to collaborate with the project, would you be interested in an external app to do different stuff in unifi? i can help in angularJs frontend...

**Comment by malle-pietje** [comment]
There is popular demand for a reporting tool: where the API Browser tool is really a tool for developers there are quite a lot of non-technical users that want to have a tool that produces tabular reports (e.g. using DataTables) on the most relevant data collections/API endpoints. Such a tool should allow the user to select/deselect columns and a select a time range (e.g. using DataRangeSelector).

I have some idea's for this but just can't find the time to develop it.

**Comment by malle-pietje** [comment]
@facuxt Would be nice if you would be able to spend some time on that...:-)

**Comment by facuxt** [comment]
maybe we can form some kind of project... i need that kind of reporting tool... with the api you can get historical data? for example from the unifi controller you just can get only 30 days ago...  There is any documentation of the api?
i'll look forward to it...  @enzogro

**Comment by malle-pietje** [comment]
Would be nice project to work on. The API can report on historical data as long as it's available from the controller. There is no documentation but I have made an effort in providing a start by adding comments to the functions in the `class.unifi.php` file.
