### ISSUE TITLE
voucher list

### ISSUE THREAD

**Issue by futabs** [malle-pietje/Unifi-API-browser#55]
is there a way to list voucher details (up/down limits, quota, notes) of single use vouchers that are used already but not yet expired?

**Comment by malle-pietje** [comment]
I don't manage any sites where we use the UniFi vouchers, instead, we use our own custom multi-device voucher solution.

I suggest you have a look through the authorizations collection to see what you find there. I wouldn't know where else to find this information; I don't believe it is specifically available anywhere through the controller UI or the Hotspot Manager UI.
