### ISSUE TITLE
Install on cloudkey?

### ISSUE THREAD

**Issue by RVN-BR** [malle-pietje/UniFi-API-browser#6]
Has anyone installed this on a cloudkey?  What would be the best way to install it in order to, for example, survive upgrades?

**Comment by malle-pietje** [comment]
Unfortunately I don't have a CloudKey to test this. Installing should be relatively easy as longs as you install the required packages (apache2, php, php-curl). I don't know how to make sure this survives a CloudKey software update.

**Comment by esellier** [comment]
This Virtual Host (folder) /usr/share/cloudkey-webui/www is configured for executing PHP though Nginx/FPM.
The virtual host is reachable though port 443 (HTTPS).

You will probably need to install php-curl 
1/ apt-get update
2/ apt-get install php-curl

No idea if that can survive a cloudkey software update

**Comment by esellier** [comment]
Be aware, you cannot use your "cloud" unifi (admin) login for use with the /api/login.
You will need to create a specific admin account.
The cloud admin user logs in through an SSO process.

At least, this is my conclusion... so far.

**Comment by mikesuding** [comment]
I also have a CloudKey controller. I would like to install your API browser on a separate ubuntu web server.  Do I need to create a separate admin account? on which device? How do I create that user?

**Comment by malle-pietje** [comment]
As long as the ubuntu machine has connectivity to port 8443 on the Cloud Key device you'll be fine.

For access you can either use the global admin account which you use to log into the controller (not the Cloud Key itself), or you can create a dedicated read-only account on your controller. The limitation with the latter approach is that such an account will only have access to a single site.
