### ISSUE TITLE
[ASK] - Command API

### ISSUE THREAD

**Issue by henryudha** [malle-pietje/Unifi-API-browser#8]
hi @malle-pietje 

this is save my life.
now, im able to create hundreds site thorugh your awesome API. thanks! :+1: 

By the way, any recoomendation where did you find the argument for each command on your API ?
i mean command like : /stat/guest , /stat/sta, /stat/user etc.
im quite strugle to find it.

once again, thanks!

cheers,
henry

**Comment by malle-pietje** [comment]
Glad to hear it is useful. Most of the endpoints I have added to the class I discovered either by closely analysing the controller UI (it also uses the API) or by receiving hints and tips from users.

**Comment by henryudha** [comment]
HI @malle-pietje 

yeah, so it means must do by our self to find other usefull command on unifi Controller.
btw i just email to support@ubuquiti.com, and they told me that they didnt have any automate system such as API.
i mean, we cannot rely to them for massive deployment.

if i found any others command, i will share to you.
hence, it will be usefull for others. 

thanks mate!

**Comment by malle-pietje** [comment]
thanks, that would be helpful!
